---
- hosts: all
  vars_files:
    - 'vars/vault.yaml'
    - 'vars/plugins.yml'
    - 'vars/remote-location.yml'

  pre_tasks:

  - name: Configure uid for docker_compose_generator
    command: id -u
    register: docker_compose_generator_uid
  - set_fact:
      docker_compose_generator_uid={{ docker_compose_generator_uid.stdout }}

  - name: Configure gid for docker_compose_generator
    command: id -g
    register: docker_compose_generator_gid
  - set_fact:
      docker_compose_generator_gid={{ docker_compose_generator_gid.stdout }}

  - name: Ensure container volume mount points are created
    file:
      path: "{{ docker_compose_generator_output_path }}/data/{{ item.service_name }}"
      state: directory
    loop: "{{ containers }}"
    loop_control:
      label: "{{ item.service_name }}"

  roles:
    - role: ironicbadger.ansible_role_docker_compose_generator
    - role: fabric
    - role: luckperms
    - role: paper
    - role: waterfall

  tasks:
    
  - name: Copy over whitelist.json file to servers
    copy:
      src: "{{ config_location }}/whitelist.json"
      dest: "{{ docker_compose_generator_output_path }}/data/{{ item.service_name }}/whitelist.json"
      owner: "{{ docker_compose_generator_uid }}"
      group: "{{ docker_compose_generator_gid }}"
    loop: "{{ containers }}"
    loop_control:
      label: "{{ item.service_name }}"
    when: item.image == 'itzg/minecraft-server'

# Uncomment Below if you wish for server network to be started at end of playbook
#  - name: Start server network using docker-compose
#    community.general.docker_compose:
#      project_src: .
