---
# geerlingguy.docker
docker_users:
  - lab

# variables for mc-waterfall-proxy configuration
server_name: "Kumpdev"
proxy_motd: "&2Kumpdev &l&7is a server network powered by Ansible!"
proxy_priority_server: "lobby"

# Variables that are used in configuration below
mc_connection_port: 25565
bedrock_connection_port: 19132
mc_version: "1.16.5"
mc_ops: "Kumpy,Fett32"

# ironicbadger.docker_compose_generator
docker_compose_generator_output_path: "~/archive/bungee"

containers:
# This container is used for the luckperms database so that the server network has one central permissions system.
# This prevents the admin from having to update permissions on all servers individually
  - service_name: luckperms-mariadb
    image: mariadb
    # active: determines whether or not container is included in resulting docker-compose file
    active: true
    environment:
      # these vars are stored in vars/vault.yaml using ansible-vault
      - "MYSQL_ROOT_PASSWORD={{ mysql_root }}"
      - "MYSQL_DATABASE={{ mysql_db }}"
      - "MYSQL_USER={{ mysql_user }}"
      - "MYSQL_PASSWORD={{ mysql_pass }}"
    volumes:
      - "./data/luckperms-mariadb/mysql:/var/lib/mysql"
    restart: unless-stopped
# This container is the waterfall proxy, it handles player connections to all servers in the network
  - service_name: mc-waterfall-proxy
  # Refer to itzg/docker-bungeecord github for documentation on env variables and container configuration below
    image: itzg/bungeecord
    active: true
    environment:
      - "TYPE=WATERFALL"
    ports:
      - "{{ mc_connection_port }}:25577"
      - "{{ bedrock_connection_port }}:19132/udp"
    volumes:
      - "./data/mc-waterfall-proxy:/server"
      - "./bungee-plugins:/plugins"
    depends_on:
      - fabric
    restart: unless-stopped
# This container is the first server you login to, it acts as a hub to access the other servers
# Ensure that the server type is always the first environment variable for proper configuration
  - service_name: vanilla
    image: itzg/minecraft-server
    active: true
    restricted: true
    environment:
      - "TYPE=FABRIC"
      - "OVERRIDE_SERVER_PROPERTIES=true"
      - "EULA=true"
      - "ONLINE_MODE=false"
      - "VERSION={{ mc_version }}"
      - "MEMORY=3G"
      - "USE_AIKAR_FLAGS=true"
      - "OPS={{ mc_ops }}"
      - "DIFFICULTY=hard"
      - "PVP=true"
      - "LEVEL=world"
      - "SPAWN_PROTECTION=0"
      - "MAX_WORLD_SIZE=15000"
      - "ENFORCE_WHITELIST=true"
      - "REMOVE_OLD_MODS=true"
      - "PLUGINS_SYNC_UPDATE=false"
    # List mods to download below"
    #- "MODS=https://github.com/OKTW-Network/FabricProxy/releases/download/v1.3.3/FabricProxy-1.3.3.jar"
    volumes:
      - "./fabric-mods:/mods"
      - "./data/vanilla:/data"
    restart: unless-stopped
  - service_name: hardcore-intermediate
    image: itzg/minecraft-server
    active: true
    restricted: true
    environment:
      - "TYPE=PAPER"
      - "OVERRIDE_SERVER_PROPERTIES=true"
      - "EULA=true"
      - "ONLINE_MODE=false"
      - "VERSION={{ mc_version }}"
      - "MEMORY=1G"
      - "USE_AIKAR_FLAGS=true"
      - "OPS={{ mc_ops }}"
      - "DIFFICULTY=hard"
      - "HARDCORE=true"
      - "SPAWN_MONSTERS=true"
      - "PVP=false"
      - "SPAWN_PROTECTION=0"
      - "MAX_WORLD_SIZE=5000"
      - "ENFORCE_WHITELIST=true"
      - "PLUGINS_SYNC_UPDATE=false"
    # List mods to download below"
    #  - "MODS=https://ci.lucko.me/job/LuckPerms/1173/artifact/bukkit/build/libs/LuckPerms-Bukkit-5.2.8.jar"
    volumes:
      - "./plugins:/plugins"
      - "./data/hardcore-intermediate:/data"
    restart: unless-stopped
  - service_name: hardcore-advanced
    image: itzg/minecraft-server
    active: true
    restricted: false
    environment:
      - "TYPE=FABRIC"
      - "OVERRIDE_SERVER_PROPERTIES=true"
      - "EULA=true"
      - "ONLINE_MODE=false"
      - "VERSION={{ mc_version }}"
      - "MEMORY=3G"
      - "USE_AIKAR_FLAGS=true"
      - "OPS={{ mc_ops }}"
      - "DIFFICULTY=hard"
      - "HARDCORE=true"
      - "SPAWN_MONSTERS=true"
      - "PVP=false"
      - "SPAWN_PROTECTION=0"
      - "MAX_WORLD_SIZE=5000"
      - "ENFORCE_WHITELIST=true"
      - "PLUGINS_SYNC_UPDATE=false"
    # List mods to download below"
    #  - "MODS=https://ci.lucko.me/job/LuckPerms/1173/artifact/bukkit/build/libs/LuckPerms-Bukkit-5.2.8.jar"
    volumes:
      - "./plugins:/plugins"
      - "./data/hardcore-advanced:/data"
    restart: unless-stopped
